"""empty message

Revision ID: cea96f58ef5d
Revises: None
Create Date: 2018-11-28 09:24:51.007923

"""

# revision identifiers, used by Alembic.
revision = 'cea96f58ef5d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('flat_num', sa.String(length=60), nullable=True),
    sa.Column('door_num', sa.String(length=160), nullable=True),
    sa.Column('webcamurl', sa.String(length=160), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_contact'), 'user', ['contact'], unique=False)
    op.create_index(op.f('ix_user_door_num'), 'user', ['door_num'], unique=True)
    op.create_index(op.f('ix_user_flat_num'), 'user', ['flat_num'], unique=True)
    op.create_index(op.f('ix_user_location'), 'user', ['location'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_user_webcamurl'), 'user', ['webcamurl'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_webcamurl'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_location'), table_name='user')
    op.drop_index(op.f('ix_user_flat_num'), table_name='user')
    op.drop_index(op.f('ix_user_door_num'), table_name='user')
    op.drop_index(op.f('ix_user_contact'), table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
